
const Committees = [
    {
        title: "General Chairs",
        content: [
            "Assoc. Prof. Dr. Nguyen Minh Hoa – Rector of Tra Vinh University",
            "Dr. Phan Quoc Nghia – Vice Rector of Tra Vinh University",
        ],
    },
    {
        title: "Program Chairs",
        content: [
            "Assoc. Prof. Dr. Nguyen Thai Son – Head of the Resource Development Institute",
            "Dr. Vo Phuoc Hung – Head of the Faculty of Engineering and Technology (Permanent)",
            "Dr. Huynh Cong Khoi – Head of Science and Technology Office, Tra Vinh University",
            "Dr. Pham Quoc Phong – Vice Head of the Faculty of Engineering and Technology",
            "Dr. Nguyen Nhut Lam – Vice Head of the Faculty of Engineering and Technology",
        ],
    },
    {
        title: "Technical Program Committee",
        content: [
            "Prof. Dr. Tang-Chieh Liu - FCU, Taiwan",
            "Prof. Dr. Cheng Ching-Hwa - FCU, Taiwan",
            "Prof. Dr. Tze-Yee-Ho - FCU, Taiwan",
            "Assoc. Prof. Dr. Do Duc Ton - Nazarbayev University, Kazakhstan",
            "Assoc. Prof. Dr. Lu Jan Huai – Taiwan",
            "Prof. Dr. Hsi-Min Chen - FCU, Taiwan",
            "Dr. Ming-Hung Wang - NCCU, Taiwan",
            "Prof. Dr. Nguyen Hieu Minh - Tra Vinh University",
            "Dr. Brian Dick - VIU, Canada",
            "Dr. Nguyen Viet Phan - Tra Vinh University",
            "Dr. Thai Minh Tuan - Can Tho University",
            "Dr. Bui Van Tung – Thai Nguyen University",
            "Dr. Dang Xuan Trong – Hositco, Vietnam",
            "Dr. Truong Van Men – Tra Vinh University",
            "Dr. Nguyen Bao An – Tra Vinh University",
            "Dr. Cao Phuong Thao – Tra Vinh University",
            "Dr. Huynh Van Hiep – Tra Vinh University",
            "Dr. Hoang Trung Kien - Tra Vinh University",
            "Dr. Le Tuong Thanh - Tra Vinh University",
            "Dr. Ngo Huu Huy - Thai Nguyen University",
            "Dr. Nguyen Duc Tue - Tra Vinh University",
            "Dr. Nguyen Thanh Tam - Tra Vinh University",
            "Dr. Nguyen Tran Diem Hanh- Tra Vinh University",
            "Dr. Nguyen Tuan Nghia - Tra Vinh University",
            "Dr. Pham Van Hoan - Tra Vinh University",
            "Dr. Tran Song Toan – Tra Vinh University",
            "Dr. Truong Van Men – Tra Vinh University",
            "Dr. Van Huu Hue - Tra Vinh University",
            "Dr. Vu Quang Hieu - Tra Vinh University",
            "Dr. Nguyen Duc Binh – Thai Nguyen University",
            "Dr. Tran Quang Quy – Thai Nguyen University",
            "Dr. Nguyen Thanh Tuan – Kien Giang Community College",
            "Dr. Do Nguyen Duy Phuong – Can Tho University",
            "Dr. Quach Ngoc Thinh – Can Tho University",
            "Dr. Nguyen Hoang Vu – Can Tho University",
            "Dr. Luong Vinh Quoc Danh – Can Tho University",
            "Dr. Le Minh Hai - Tra Vinh University",
            "Dr. Nguyen Xuan Son - Tra Vinh University",
            "Dr. Nguyen Viet Tuan - Tra Vinh University",
            "Dr. Chu Viet Cuong - Tra Vinh University",
            "M.Sc. Phan Tan Tai - Tra Vinh University",
        ],
    },
    {
        title: "Secretary",
        content: [
            "MEng. Ngo Thanh Ha - Tra Vinh University;",
            "MEng. Ha Thi Thuy Vi - Tra Vinh University;",
            "MEng. Bui Thi Thu Thuy - Tra Vinh University;",
            "MEng. Huynh Thi My Dung - Tra Vinh University;",
        ],
    },
];

export {Committees}