
const Committees = [
    {
        title: "Chairman Program Committee",
        content: [
            "Assoc. Prof. Dr. Nguyen Minh Hoa – Rector of Tra Vinh University",
        ],
    },
    {
        title: "Deputy Head of Organizing Committee, Program Committee Member",
        content: [
            "Dr. Phan Quoc Nghia – Vice Rector of Tra Vinh University",
            "Dr. Vo Phuoc Hung – Head of the Faculty of Engineering and Technology (Permanent)",
            "Dr. Huynh Cong Khoi – Head of Science and Technology Office, Tra Vinh University",
        ],
    },
    {
        title: "Program Committee Head",
        content: [
            "Dr. Nguyen Nhut Lam – Vice Head of the Faculty of Engineering and Technology",
        ],
    },
    {
        title: "Co-Deputy Program Committee Heads",
        content: [
            "Prof. Assoc. Dr. Nguyen Thai Son – Head of the Resource Development Institute",
            "Dr. Pham Quoc Phong – Vice Head of the Faculty of Engineering and Technology",
            "Dr. Truong Van Men – Vice Head of the Mechanical Engineering Department",
            "Dr. Nguyen Bao Linh – Vice Head of the Information Technology Department",
            "Dr. Cao Phuong Thao – Head of the Electrical and Electronic Department",
            "Dr. Huynh Van Hiep – Head of the Construction Department",
        ],
    },
    {
        title: "Technical Program Committee",
        content: [
            "Prof. Dr. Tang-Chieh Liu - FCU, Taiwan",
            "Prof. Dr. Cheng Ching-Hwa - FCU, Taiwan",
            "Prof. Dr. Nguyen Tat Dac - Tra Vinh University",
            "Prof. Dr. Tze-Yee-Ho - FCU, Taiwan",
            "Assoc. Prof. Dr. Do Duc Ton - Nazarbayev University, Kazakhstan",
            "Assoc. Prof. Dr. Lu Jan Huai – Taiwan",
            "Prof. Dr. Hsi-Min Chen - FCU, Taiwan",
            "Dr. Ming-Hung Wang - NCCU, Taiwan",
            "Prof. Dr. Nguyen Hieu Minh - Tra Vinh University",
            "Dr. Brian Dick - VIU, Canada",
            "Dr. Nguyen Viet Phan - Tra Vinh University",
            "Dr. Thai Minh Tuan - Can Tho University",
            "Dr. Bui Van Tung – University of Information Technology and Communication - Thai Nguyen University",
            "Dr. Dang Xuan Trong – Hositco, Vietnam",
            "Dr. Hoang Trung Kien - Tra Vinh University",
            "Dr. Le Tuong Thanh - Tra Vinh University",
            "Dr. Ngo Huu Huy - University of Information Technology and Communication - Thai Nguyen University",
            "Dr. Nguyen Bao Linh – Tra Vinh University",
            "Dr. Nguyen Duc Tue - Tra Vinh University",
            "Dr. Nguyen Thanh Tam - Tra Vinh University",
            "Dr. Nguyen Tran Diem Hanh- Tra Vinh University",
            "Dr. Nguyen Tuan Nghia - Tra Vinh University",
            "Dr. Pham Van Hoan - Tra Vinh University",
            "Dr. Tran Song Toan – Tra Vinh University",
            "Dr. Truong Hoang Linh - Tra Vinh University",
            "Dr. Truong Van Men – Tra Vinh University",
            "Dr. Van Huu Hue - Tra Vinh University",
            "Dr. Vu Quang Hieu - Tra Vinh University",
            "Dr. Nguyen Duc Binh – Thai Nguyen University",
            "Dr. Tran Quang Quy – Thai Nguyen University",
            "Dr. Nguyen Thanh Tuan – Kien Giang Community College",
            "Dr. Do Nguyen Duy Phuong – Can Tho University",
            "Dr. Quach Ngoc Thinh – Can Tho University",
            "Dr. Nguyen Hoang Vu – Can Tho University",
            "Dr. Luong Vinh Quoc Danh – Can Tho University",
            "Dr. Le Minh Hai - Tra Vinh University",
            "Dr. Nguyen Xuan Son - Tra Vinh University",
            "Dr. Nguyen Viet Tuan - Tra Vinh University",
            "Dr. Chu Viet Cuong - Tra Vinh University",
            "M.Sc. Phan Tan Tai - Tra Vinh University",
        ],
    },
    {
        title: "Secretary",
        content: [
            "M.Sc. Ngo Thanh Ha – Lecturer of the Department of Mechanical Engineering",
            "M.Sc. Ha Thi Thuy Vi – Lecturer of the Department of Information Technology",
            "M.Sc. Bui Thi Thu Thuy – Lecturer of the Department of Electrical and Electronic",
            "M.Sc. Huynh Thi My Dung – Lecturer of the Department of Construction",
        ],
    },
];

export {Committees}